### PR TITLE
clang toolchain: enable assembler (llvm-as)

### PR DESCRIPTION
**Pull request by imphil**

### CODE REVIEW

**Comment by imphil** [comment]
A more experimental patch to align the clang-based toolchain with the GCC one after the changes in #33. Let's see what CI has to say.

**Comment by asb** [comment]
llvm-as is just for assembling .ll to bitcode. llvm-mc would be closer to GNU as, but I think the general recommendation is to use the clang driver.

**Comment by imphil** [comment]
Ah ok. Let's abandon this then, the current OTBN tooling is only tested with the GNU assembler anyways currently.

**Comment by lenary** [comment]
Yeah, I've suggested the correct approach in the other PR.

**Pull request closed without merging**
