### PR TITLE
Add toolchain for Muntjac v0.1

### PR DESCRIPTION
**Pull request by db434**
Adding a RV64I build. No idea what I'm doing - hopefully I haven't copy/pasted anything unnecessary.

### CODE REVIEW

**Comment by lenary** [comment]
@db434 Have you been able to test the built toolchain yet?

**Comment by db434** [comment]
@lenary I've successfully compiled (simple) programs, but I'm still working on a platform where I can execute them, so I don't know for sure that the toolchain is working correctly.

**Comment by lenary** [comment]
@db434 Any progress? We're likely to tag a new release of the toolchain soon, so this could be included if you feel it's working for you :)

**Comment by lenary** [comment]
@db434 btw, feel free to squash commits and force-push to your branch - at lowRISC we tend to rebase PRs when we merge them, keeping the history and commit messages.

**Comment by db434** [comment]
Okay, I've made some tweaks and done some testing (thanks @nbdd0121), and everything appears to be working. We're not 100% sure about the LLVM toolchain because it contains binaries named `...-gcc`, but I guess that's normal?

Thanks for all your tips.

**Comment by lenary** [comment]
The LLVM Toolchain contains both gcc and clang/llvm binaries, so that's not a problem, it's intended behaviour!

**Comment by lenary** [comment]
This will be part of the `20200904-1` toolchain once it builds - expect it in about 3 hours.

**Comment by lenary** [comment]
Tarballs are now available here: https://github.com/lowRISC/lowrisc-toolchains/releases/tag/20200904-1

**Pull request merged**
